services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
